import express from "express";

import activityRouter from "./api/v1/activityRouter.js";
import adminRouter from "./api/v1/adminRouter.js";
import authRouter from "./api/v1/authRouter.js";
import checkinRouter from "./api/v1/checkinRouter.js";
import commentRouter from "./api/v1/commentRouter.js";
import devRouter from "./api/v1/devRouter.js";
import eventRouter from "./api/v1/eventRouter.js";
import feedRouter from "./api/v1/feedRouter.js";
import generalRouter from "./api/v1/generalRouter.js";
import homemadeRouter from "./api/v1/homemadeRouter.js";
import listRouter from "./api/v1/listRouter.js";
import mapRouter from "./api/v1/mapRouter.js";
import mediaRouter from "./api/v1/mediaRouter.js";
import notificationRouter from "./api/v1/notificationRouter.js";
import placeRouter from "./api/v1/placeRouter.js";
import reactionRouter from "./api/v1/reactionRouter.js";
import reviewRouter from "./api/v1/reviewRouter.js";
import rewardRouter from "./api/v1/rewardRouter.js";
import transactionRouter from "./api/v1/transactionRouter.js";
import uploadRouter from "./api/v1/uploadRouter.js";
import userRouter from "./api/v1/userRouter.js";
import webhookRouter from "./api/v1/webhookRouter.js";

const router = express.Router();

router.use("/activities", activityRouter);
router.use("/auth", authRouter);
router.use("/events", eventRouter);
router.use("/media", mediaRouter);
router.use("/upload", uploadRouter);
router.use("/users", userRouter);
router.use("/places", placeRouter);
router.use("/reviews", reviewRouter);
router.use("/homemades", homemadeRouter);
router.use("/reactions", reactionRouter);
router.use("/general", generalRouter);
router.use("/checkins", checkinRouter);
router.use("/comments", commentRouter);
router.use("/map", mapRouter);
router.use("/feeds", feedRouter);
router.use("/notifications", notificationRouter);
router.use("/lists", listRouter);
router.use("/rewards", rewardRouter);
router.use("/dev", devRouter);
router.use("/admin", adminRouter);
router.use("/webhooks", webhookRouter);
router.use("/transactions", transactionRouter);

export default router;
